import '../../common/span.dart';
import 'diagnostic_code.dart';
import 'diagnostic_severity.dart';

/// Represents an additional label for a specific part of the code
/// that provides context to a diagnostic message.
///
/// This typedef is used within [Diagnostic] to highlight secondary locations
/// in the source code that are relevant to the primary diagnostic message.
///
/// Fields:
/// - `span`: The [Span] indicating the exact location in the code.
/// - `message`: A concise message explaining the context of this label.
///
/// Example:
/// ```dart
/// DiagnosticLabel myLabel = (
///   span: mySourceFile.span(10, 20),
///   message: 'This is related to the error'
/// );
/// ```
typedef DiagnosticLabel = ({Span span, String message});

/// Base class for all semantic diagnostics (errors, warnings, hints).
///
/// This abstract class provides the common structure for all diagnostic
/// messages generated by the Lake language compiler/analyzer. It includes
/// information about the primary location of the issue, a descriptive message,
/// severity, an optional unique code, and additional contextual information.
base class Diagnostic {
  /// Creates a new [Diagnostic] instance.
  ///
  /// - Parameters:
  ///   - [span]: The main location in the source code where the diagnostic
  /// originates. This is the most important piece of location information.
  ///   - [message]: The main message describing the diagnostic, intended to be
  /// user-friendly and actionable.
  ///   - [severity]: The [DiagnosticSeverity] of the diagnostic, defaulting to
  /// [DiagnosticSeverity.error] if not specified.
  ///   - [code]: An optional unique code for the diagnostic (e.g., "E1001",
  /// "W2001"). Useful for programmatic identification and documentation links.
  ///   - [labels]: A list of additional [DiagnosticLabel]s providing context
  /// to parts of the code related to the primary span. Defaults to an empty
  /// list.
  const Diagnostic({
    required this.message,
    required this.span,
    required this.filePath,
    this.severity = DiagnosticSeverity.error,
    this.code,
    this.labels = const [],
  });

  /// The main message describing the diagnostic.
  /// This message should be clear and concise, explaining what went wrong.
  final String message;

  /// The main location in the source code where the diagnostic originates.
  /// This is typically the most relevant part of the code for the issue.
  final Span span;

  /// The absolute path of the source file where the diagnostic was generated.
  /// This is useful for identifying the file in larger projects or when
  /// reporting diagnostics across multiple files.
  final String filePath;

  /// The severity of the diagnostic (e.g., error, warning, info, fatal).
  /// Determines how the diagnostic should be presented to the user and its
  /// impact on compilation.
  final DiagnosticSeverity severity;

  /// An optional unique code for the diagnostic (e.g., "E1001", "W2001").
  /// This allows users to look up more information about a specific issue.
  final DiagnosticCode? code;

  /// A list of additional [DiagnosticLabel]s providing context.
  /// These labels highlight other relevant parts of the code that contribute
  /// to the diagnostic message.
  final List<DiagnosticLabel> labels;
}
