name: lake
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/pro100andrey/lake/packages/lake
issue_tracker: https://github.com/pro100andrey/lake/issues
homepage: https://github.com/pro100andrey/lake
documentation: https://github.com/pro100andrey/lake/blob/master/lake/README.md

environment:
  sdk: ^3.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

# Add regular dependencies here.
dependencies:
   json_annotation: ^4.8.1
   orm: ^3.4.3

dev_dependencies:
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  lint:
    git:
      url: "https://github.com/pro100andrey/lint.git"
  test: ^1.24.3

dependency_overrides:
  http: ^1.0.0