name: lake_cli
description: Lake CLI.
version: 0.0.1

repository: https://github.com/pro100andrey/lake/packages/lake_cli
issue_tracker: https://github.com/pro100andrey/lake/issues
homepage: https://github.com/pro100andrey/lake
documentation: https://github.com/pro100andrey/lake/blob/master/lake_cli/README.md

environment:
  sdk: ^3.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  args: ^2.4.2
  cli_completion: ^0.3.0
  code_builder: ^4.5.0
  dcli: ^2.3.0
  dotenv: ^4.1.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  mason_logger: ^0.2.6
  protoc_plugin: ^20.0.1
  pub_updater: ^0.3.0

dev_dependencies:
  build_runner: ^2.4.5
  build_verify: ^3.1.0
  build_version: ^2.1.1
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  pro_lints: ^2.0.1
  test: ^1.24.2
  
executables:
  lake: lake_cli
