name: lake_cli
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
   analyzer: ^5.12.0
   args: ^2.4.1
   code_builder: ^4.4.0
   colorize: ^3.0.0
   path: ^1.8.3
   yaml: ^3.1.2

dev_dependencies:
  lint:
    git:
      url: "https://github.com/pro100andrey/lint.git"
  test: ^1.24.3

executables: 
  lake: lake_cli
