name: lake_cli
description: A Very Good Project created by Very Good CLI.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.1
  cli_completion: ^0.3.0
  code_builder: ^4.5.0
  dcli: ^2.2.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  mason_logger: ^0.2.6
  protoc_plugin: ^20.0.1
  pub_updater: ^0.3.0

dev_dependencies:
  build_runner: ^2.4.5
  build_verify: ^3.1.0
  build_version: ^2.1.1
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  lint:
    git:
      url: "https://github.com/pro100andrey/lint.git"
  mocktail: ^0.3.0
  test: ^1.24.2

executables:
  lake: lake_cli
