name: lake_cli
description: A Very Good Project created by Very Good CLI.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.1
  cli_completion: ^0.3.0
  dcli: ^1.36.2
  mason_logger: ^0.2.5
  pub_updater: ^0.3.0

dev_dependencies:
  build_runner: ^2.4.4
  build_verify: ^3.1.0
  build_version: ^2.1.1
  lint:
    git:
      url: "https://github.com/pro100andrey/lint.git"
  mocktail: ^0.3.0
  test: ^1.24.2

executables:
  lake: lake_cli
