name: lake_lang
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.5

dependencies:
  source_span: ^1.10.2
  
dev_dependencies:
  benchmark_harness: ^2.4.0
  pro_lints: ^6.1.0
  test: ^1.31.1
