name: lake_lang
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.5

dependencies:
  equatable: ^2.0.8
  petitparser: ^7.0.2
  source_span: ^1.10.2
  
dev_dependencies:
  pro_lints: ^5.2.0
  test: ^1.31.1
