// Mocks generated by Mockito 5.4.6 from annotations
// in lake_lang/test/analyzer/analysis/analysis_cache_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:lake_lang/src/analyzer/diagnostics/diagnostic.dart' as _i7;
import 'package:lake_lang/src/analyzer/engine/semantic_info.dart' as _i6;
import 'package:lake_lang/src/analyzer/symbols/symbol_table.dart' as _i2;
import 'package:lake_lang/src/ast/ast_visitor.dart' as _i4;
import 'package:lake_lang/src/ast/nodes/ast_nodes.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSymbolTable_0 extends _i1.SmartFake implements _i2.SymbolTable {
  _FakeSymbolTable_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DocumentNode].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentNode extends _i1.Mock implements _i3.DocumentNode {
  @override
  List<_i3.HeaderNode> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <_i3.HeaderNode>[],
            returnValueForMissingStub: <_i3.HeaderNode>[],
          )
          as List<_i3.HeaderNode>);

  @override
  List<_i3.DefinitionNode> get definitions =>
      (super.noSuchMethod(
            Invocation.getter(#definitions),
            returnValue: <_i3.DefinitionNode>[],
            returnValueForMissingStub: <_i3.DefinitionNode>[],
          )
          as List<_i3.DefinitionNode>);

  @override
  List<Object?> get props =>
      (super.noSuchMethod(
            Invocation.getter(#props),
            returnValue: <Object?>[],
            returnValueForMissingStub: <Object?>[],
          )
          as List<Object?>);

  @override
  ({int end, int start}) get span =>
      (super.noSuchMethod(
            Invocation.getter(#span),
            returnValue: (end: 0, start: 0),
            returnValueForMissingStub: (end: 0, start: 0),
          )
          as ({int end, int start}));

  @override
  bool get stringify =>
      (super.noSuchMethod(
            Invocation.getter(#stringify),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  T accept<T>(_i4.AstVisitor<T>? visitor) =>
      (super.noSuchMethod(
            Invocation.method(#accept, [visitor]),
            returnValue: _i5.dummyValue<T>(
              this,
              Invocation.method(#accept, [visitor]),
            ),
            returnValueForMissingStub: _i5.dummyValue<T>(
              this,
              Invocation.method(#accept, [visitor]),
            ),
          )
          as T);
}

/// A class which mocks [SemanticInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockSemanticInfo extends _i1.Mock implements _i6.SemanticInfo {
  @override
  _i2.SymbolTable get localSymbolTable =>
      (super.noSuchMethod(
            Invocation.getter(#localSymbolTable),
            returnValue: _FakeSymbolTable_0(
              this,
              Invocation.getter(#localSymbolTable),
            ),
            returnValueForMissingStub: _FakeSymbolTable_0(
              this,
              Invocation.getter(#localSymbolTable),
            ),
          )
          as _i2.SymbolTable);

  @override
  List<_i7.Diagnostic> get diagnostics =>
      (super.noSuchMethod(
            Invocation.getter(#diagnostics),
            returnValue: <_i7.Diagnostic>[],
            returnValueForMissingStub: <_i7.Diagnostic>[],
          )
          as List<_i7.Diagnostic>);
}
